name: socialapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sizer:
  velocity_x:
  image_picker:
  image_cropper:
  photo_view:


  flutter_staggered_grid_view: ^0.4.0
  cloud_firestore:
  firebase_storage:
  provider:
  swipe_to:
  overlay_support:
  connectivity_plus:
  google_sign_in:

  firebase_auth:
  firebase_core:
  shared_preferences:
  fluttertoast:
  http:
  get:
  floor:

  auto_size_text:
  simple_s3:
  file_picker:
  api_cache_manager:
  flutter_native_image:
  dotted_border:
  audio_waveforms:
  path_provider:

  cached_network_image:
  animated_bottom_navigation_bar:


  uuid:
  flutter_pdfview:
  video_player:

  permission_handler:
  transparent_image:
  just_audio:
  audio_video_progress_bar:
  audioplayers:
  record_mp3:
  social_media_recorder:
  flutter_svg:
  chewie:
  flutter_spinkit:
  expand_tap_area:
  external_path:
  geolocator:
  google_maps_flutter:
  emoji_picker_flutter:
  intl:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator:
  build_runner:


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - asset/images/
   - asset/images/floating.png
   - asset/images/homepageone.svg
   - asset/images/homepagefour.svg
   - asset/images/homepagetwo.svg
   - asset/images/homepagethree.svg
   - asset/images/noti.svg
   - asset/images/love.svg
   - asset/images/comment.svg
   - asset/images/bookmark.svg
   - asset/images/newnoti.svg
   - asset/images/searc.svg
   - asset/images/back_arow.svg
   - asset/images/nesend.svg
   - asset/images/emojiicon.svg
   - asset/images/camerachat.svg
   - asset/images/150x150.png
   - asset/images/auidochat.svg
   - asset/images/thrdchat.svg
   - asset/images/lastchat.svg
   - asset/images/firstchatt.svg
   - asset/images/secndchatt.svg
   - asset/images/trash_containerr.png
   - asset/images/trash_coverr.png
   - asset/images/nochatpic.svg
   - asset/images/echoespic.svg
   - asset/images/nofollowe.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyIcons
      fonts:
        - asset: icons/MyIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
